### ISSUE TITLE
Wrong version number

### ISSUE THREAD

**Issue by chevcheli0s** [kzalewski/openssl-1.1.1#1]
Under windows displayed 1.1.1z instead of 1.1.1za
![image](https://github.com/user-attachments/assets/ce9d8582-66e8-4d67-9f72-a07432f156fb)
I think bug in mkrc.pl

**Comment by kzalewski** [comment]
I have no idea how the OpenSSL version number is generated on Windows.  If you could point me to the file(s) that need to be modified, I will be happy to incorporate that into my patches.  For now, I am focused solely on the Linux operating system.

**Comment by kzalewski** [comment]
I merged in a PR that might address the issue that you reported.  Please see  https://github.com/kzalewski/openssl-1.1.1/commit/2a0d6942c4c816f7a50a27f2136ae97c11d3f10a

**Comment by kzalewski** [comment]
@chevcheli0s , did you have a chance to try out my latest release (1.1.1zb-patch1)?  I'd like to know if it resolves this Windows DLL version problem, so I can close this issue.

**Comment by chevcheli0s** [comment]
> @chevcheli0s , did you have a chance to try out my latest release (1.1.1zb-patch1)? I'd like to know if it resolves this Windows DLL version problem, so I can close this issue.

compile it with 
```
./Configure mingw64 shared --cross-compile-prefix=x86_64-w64-mingw32-
make
```
Now all is fine
![image](https://github.com/user-attachments/assets/6bc6224a-b3e3-4894-a005-5a30bec612ac)

**Comment by kzalewski** [comment]
Thank you for testing and verifying the fix.
